### ISSUE TITLE
Create container from IServiceCollection

### ISSUE THREAD

**Issue by totht91** [unitycontainer/microsoft-dependency-injection#11]
I want to create an `IUnityContainer` instance from an `IServiceCollection` but currently only the `IServiceProvider  ServiceProviderExtensions.BuildServiceProvider(this IServiceCollection services, bool validateScopes = false)` API is public. I would like to use `IUnityContainer ServiceProviderFactory.CreateBuilder(IServiceCollection services)` method, so could you make it public visible?

[OFF] Maybe this issue is related: https://github.com/PrismLibrary/Prism/issues/1352

**Comment by ENikS** [comment]
[Done](https://www.nuget.org/packages/Unity.Microsoft.DependencyInjection/2.0.6)

**Comment by totht91** [comment]
Thanks
