### ISSUE TITLE
Write unit tests for this library.

### ISSUE THREAD

**Issue by axelgenus** [unitycontainer/microsoft-dependency-injection#2]
We need a couple of unit tests to ensure that everything is working fine.

**Comment by ENikS** [comment]
MS offers this package: https://www.nuget.org/packages/Microsoft.Extensions.DependencyInjection.Specification.Tests

We could grab v1.1.1 and see if it is compatible. 

I know that current Unity fails 1/3 of these in the 2.0.0 version.  You can check it out [here](https://github.com/unitycontainer/unity/tree/experimental/src/Unity.Microsoft.DependencyInjection)

**Comment by axelgenus** [comment]
PR #3 introduced base testing for the library.
