### ISSUE TITLE
HttpClientFactory not working

### ISSUE THREAD

**Issue by pksorensen** [unitycontainer/microsoft-dependency-injection#28]
I have not been able to create a repro for this yet, so this is just to gather information for now.

![image](https://user-images.githubusercontent.com/2718591/48840474-084a6680-ed8f-11e8-8e0e-87a063dc5fd6.png)

This is the ServiceProvider of a httpclientfactory dependency of a custom service constructor.

and then later when it actually is used the SP is null

![image](https://user-images.githubusercontent.com/2718591/48840565-52cbe300-ed8f-11e8-950b-e244ba6e132b.png)

Need to figure out why this can happen, because it will throw exceptions otherwise. Possible issue is that the sp for the httpclientfactory is disposed. (will update with i have more info)

**Comment by pksorensen** [comment]
Reproduced it to the following unittest:

```
        [TestMethod]
        public void Test2_failing()
        {

            var serviceColection = new ServiceCollection();

           
            serviceColection.AddHttpClient();

            var container = new UnityContainer().CreateChildContainer();


            var factory = new ServiceProviderFactory(container);

            var sp = factory.CreateServiceProvider(serviceColection);
            var scopeFactory = sp.GetRequiredService<IServiceScopeFactory>();
            using (var scope = scopeFactory.CreateScope())
            {
                var httpFactory = scope.ServiceProvider.GetRequiredService<IHttpClientFactory>();

                var sp1 = httpFactory.GetType().GetField("_services", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance)?.GetValue(httpFactory) as IServiceProvider;
                var c1 = sp1.GetType().GetField("_container", BindingFlags.NonPublic | BindingFlags.Instance).GetValue(sp1);
                Assert.IsNotNull(c1,"In scope");

            }

            {
                var httpFactory = sp.GetRequiredService<IHttpClientFactory>();
                var sp1 = httpFactory.GetType().GetField("_services", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance)?.GetValue(httpFactory) as IServiceProvider;
                var c1 = sp1.GetType().GetField("_container", BindingFlags.NonPublic | BindingFlags.Instance).GetValue(sp1);
                Assert.IsNotNull(c1, "after scope");
            }

        }
```

**Comment by ENikS** [comment]
Where is this coming from ``var factory = new ServiceProviderFactory(container);``?
[ServiceProviderFactory](https://github.com/unitycontainer/microsoft-dependency-injection/blob/master/src/ServiceProviderFactory.cs) does not have a constructor with container as parameter

**Comment by ENikS** [comment]
I do not think it is a bug. It behaves as designed:
``IHttpClientFactory`` is a singleton but first resolved within the scope. As result it provided scoped ``IServiceProvider``. 
When it goes out of scope it rightfully discards the container but being retained by instance of ``IHttpClientFactory``

Next time ``IHttpClientFactory`` is requested it returns existing instance with invalid reference to long gone scope.

To fix the issue you need to resolve ``IHttpClientFactory`` in proper service provider:
```
var serviceCollection = new ServiceCollection();


serviceCollection.AddHttpClient();

IUnityContainer container = new UnityContainer().CreateChildContainer();

var factory = new ServiceProviderFactory(container);

var sp = factory.CreateServiceProvider(serviceCollection);
var scopeFactory = sp.GetRequiredService<IServiceScopeFactory>();
var httpFactory0 = sp.GetRequiredService<IHttpClientFactory>();
using (var scope = scopeFactory.CreateScope())
{
    var httpFactory = scope.ServiceProvider.GetRequiredService<IHttpClientFactory>();

    var sp1 = httpFactory.GetType().GetField("_services", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance)?.GetValue(httpFactory) as IServiceProvider;
    var c1 = sp1.GetType().GetField("_container", BindingFlags.NonPublic | BindingFlags.Instance).GetValue(sp1);
    Assert.NotNull(c1); // "In scope"

}

{
    var httpFactory = sp.GetRequiredService<IHttpClientFactory>();
    var sp1 = httpFactory.GetType().GetField("_services", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance)?.GetValue(httpFactory) as IServiceProvider;
    var c1 = sp1.GetType().GetField("_container", BindingFlags.NonPublic | BindingFlags.Instance).GetValue(sp1);
    Assert.NotNull(c1); // "after scope"
}

```

**Comment by pksorensen** [comment]
That was also what i ended up doing (resolving it in my application startup code).

That said, i do not think that is how build in DI is behaving in aspnet core. It works even though the first resolution happens in a scope. 

And thats what people would expect when swapping to a 3th party container i assume.

**Comment by ENikS** [comment]
I do not think there is an easy way for Unity to address it. Unfortunately...

**Comment by pksorensen** [comment]
I agree. 

One really just need to be an expert and have in dept knowledge to know these things, which takes time :)

Thanks
