### ISSUE TITLE
Question about ServiceProvider default lifetime

### ISSUE THREAD

**Issue by kshi219** [unitycontainer/microsoft-dependency-injection#39]
Hi,

What is the motivation is behind using ExternallyControlledLifetimeManager in the constructor of ServiceProvider? Is it intended that the constructed service provider be explicitly injected by the user into the container with a some chosen lifetime? 

Thanks!

**Comment by ENikS** [comment]
It is registered several times by different interfaces. To prevent multiple disposals external lifetime is used

**Comment by kshi219** [comment]
I see. So in our use case we ran into an issue where unless we explicitly held onto a reference of the service provider returned by BuildServiceProvider, like by injecting it into our unity container with ContainerControlledLifeTimeManager, the ServiceProvider would be garbage collected and cause runtime issues. Which led to to this question about what the intended usage pattern should be.

**Comment by ENikS** [comment]
I would need a code sample to verify your scenario and fix the issue

**Comment by kshi219** [comment]
Hi, was away over the weekend, will make one up soon

**Comment by kshi219** [comment]
#40 seems to have a repro attached that captures the essence of what we saw, will not be making another one up, thanks!
