### ISSUE TITLE
Compilation errors

### ISSUE THREAD

**Issue by Jeromino** [unitycontainer/microsoft-dependency-injection#45]
I wanted to look at issue #40 but the code doesn't compile on both active branches because of references to a NoValue property that doesn't exist.

**Comment by ENikS** [comment]
What code, on what branches? Could you be more specific?

Get Unity v5 clone, init submodules and try again.

**Comment by Jeromino** [comment]
Sorry about that I didn't realize submodules were required for the integration of Unity v5.

I'll rather pull a branch from the revision of v5.10.2.185 as I just need an hotfix.
