### ISSUE TITLE
Generic service registered as singleton is behaving as transient

### ISSUE THREAD

**Issue by thorhj** [unitycontainer/microsoft-dependency-injection#46]
I have a service with this signature:

```c#
public class StorageService<T> : IStorageService<T> { ... }
```

The service is registered to Unity, and Unity is added as the service provider for ASP.NET in Program.cs:

```c#
public static IWebHostBuilder CreateWebHostBuilder(string[] args)
{
    var container = new UnityContainer();

    container.RegisterType(typeof(IStorageService<>), typeof(StorageService<>), new SingletonLifetimeManager());

    return WebHost.CreateDefaultBuilder(args)
        .UseUnityServiceProvider(container)
        .UseStartup<Startup>();
}
```
The service in injected into a controller using constructor injection:
```c#
public AnotherController(IStorageService<string> storageService)
{
    _storageService = storageService;
}
```
**Expected behavior:** Each time the controller is instantiated, the same instance of IStorageService<string> should be used.

**Actual behavior:** Each time this controller is instantiated, a new instance of IStorageService<string> is created an injected into the controller.

I suspect that the concrete instance is being registered in a child container, and does not reach the global scope. I am only seeing this behavior when using dependencies through Microsoft DI. I could not reproduce the same issues using `ChildContainer`s on a regular project.

**Packages:**
- Microsoft.AspNetCore.App 2.2.0
- Unity 5.10.3
- Unity.Microsoft.DependencyInjection 5.10.2

**Comment by thorhj** [comment]
The issue can be seen in this project: https://github.com/thorhj/unity-aspnet-core

Every time you hit an endpoint, a new `StorageService` is instantiated.

**Comment by thorhj** [comment]
Also note that this Microsoft DI native registration is working as expected:
```c#
services.AddSingleton(typeof(IStorageService<>), typeof(StorageService<>));
```

**Comment by thorhj** [comment]
This failing test shows the problem:

```c#
[Fact]
public void GenericSingletonServicesComeFromRootProvider()
{
    TestServiceCollection services = new TestServiceCollection();
    services.AddSingleton(typeof(IFakeOpenGenericService<>), typeof(FakeOpenGenericService<>));
    IServiceProvider serviceProvider = this.CreateServiceProvider((IServiceCollection)services);
    FakeOpenGenericService<object> fakeService1;
    using (IServiceScope scope = serviceProvider.CreateScope())
    {
        fakeService1 = (FakeOpenGenericService<object>)Assert.IsType<FakeOpenGenericService<object>>((object)scope.ServiceProvider.GetService<IFakeOpenGenericService<object>>());
    }

    FakeOpenGenericService<object> fakeService2;
    using (IServiceScope scope = serviceProvider.CreateScope())
    {
        fakeService2 = (FakeOpenGenericService<object>)Assert.IsType<FakeOpenGenericService<object>>((object)scope.ServiceProvider.GetService<IFakeOpenGenericService<object>>());
    }

    Assert.Same((object)fakeService1, (object)fakeService2);
}
```

**Comment by Rfaering** [comment]
I spend some time, trying to figure out what was going on. 

It seems to me, that the bug is related to an issue in unity, so I created an issue on their Github, with a few examples of the odd behavior

If it turns out to be the expected behavior from their end, it would be nice with a workaround in this library 

https://github.com/unitycontainer/unity/issues/298

**Comment by Rfaering** [comment]
@ENikS  - If you are interested, here is a branch from v5.x that works around the problem of doing registrations on the sub container

[microsoft-dependency-injection.zip](https://github.com/unitycontainer/microsoft-dependency-injection/files/3224095/microsoft-dependency-injection.zip)

**Comment by thorhj** [comment]
@ENikS feel free to close. The resolution of https://github.com/unitycontainer/unity/issues/298 has solved this issue.
