### ISSUE TITLE
ChildContainer

### ISSUE THREAD

**Issue by xcap2000** [unitycontainer/microsoft-dependency-injection#49]
Does this project use a ChildContainer for each request?

**Comment by ENikS** [comment]
The container does not control scope (child container) creation. It is determined by the aspnet implementation.

The container implements factory interfaces to be used by the framework to create scopes and etc.

**Comment by xcap2000** [comment]
Even though my question was too shallow by reading your comments and reading the source code I think got what I wanted. But just to make sure, whenever MVC uses a scoped context a child container will be created right? (at least is what I can infer from microsoft-dependency-injection/src/ServiceProvider.cs)

**Comment by ENikS** [comment]
Your guess is as good as mine. It changes from version to version.
I do not monitor .net internals on a regular basis.

**Comment by ENikS** [comment]
> But just to make sure, whenever MVC uses a scoped context a child container will be created right?

That is correct

**Comment by xcap2000** [comment]
@ENikS Thank you very much!
