### ISSUE TITLE
Unable to add Unity to HostBuilder based application

### ISSUE THREAD

**Issue by StuffOfInterest** [unitycontainer/microsoft-dependency-injection#62]
The `UseUnityServiceProvider` extension method only works with `IWebHostBuilder` based applications.  I'm working on a console application that relies on `HostBuilder` (and the exported `IHostBuilder` interface) for creating an application.  There needs to be a set of extension methods and required factory objects to allow using Unity with `IHostBuilder` based applications the same way it is used with `IWebHostBuilder` based applications.

**Comment by ENikS** [comment]
Fixed in  [5.11.2](https://www.nuget.org/packages/Unity.Microsoft.DependencyInjection)
