### ISSUE TITLE
ConfigureContainer(IUnityContainer container) dont work in Startup class

### ISSUE THREAD

**Issue by PeterOscarsson** [unitycontainer/microsoft-dependency-injection#70]
Take the default Unity Sample application for MS DI and add
public void ConfigureContainer(IUnityContainer container) to the startup class 

=> InvalidCastException on CreateHostBuilder.

I have also tried to use the constructur to inject IUnityContainer but it wont work either.
(Should work according to doc)

Something seems to be broken.

NetCore 3.1 and Unity 5.11.4

Best regards.

**Comment by ENikS** [comment]
Did you try [this example](https://github.com/unitycontainer/examples/tree/master/src/web/ASP.Net.Unity.Example)?

**Comment by PeterOscarsson** [comment]
Yes, I used that exact example, and just added

public void ConfigureContainer(IUnityContainer container) 

to startup.cs

Not Working. :-(
