### ISSUE TITLE
Provide an event for CreateChildContainer

### ISSUE THREAD

**Issue by rizi** [unitycontainer/microsoft-dependency-injection#76]
Hi,
Is there a way to subscribe to an event when a child container is created or any other way to get notified?
We need to subscribe to this event and add some custom UnityContainerExtension.

br

**Comment by ENikS** [comment]
https://github.com/unitycontainer/container/blob/009be65f835ecc3c2babd55cf79696649a7ce53b/src/Extension/ExtensionContext.cs#L84

**Comment by rizi** [comment]
@ENikS thx for the fast reply, can you tell me how to subscribe to this event, I can't find a proper way, the only usage of ExtensionContext seems to be in the ContainerContext (https://github.com/unitycontainer/container/blob/b737bb32f17c39b174103aae86b63b95b302636a/src/UnityContainer.ContainerContext.cs), but that's a private class.

So it seems I can't find a hook to register to this event.

br

**Comment by ENikS** [comment]
You need to create an Unity Extension, add it to the container and handle the event from your extension.

**Comment by rizi** [comment]
> You need to create an Unity Extension, add it to the container and handle the event from your extension.

thx
