### ISSUE TITLE
How could I use PerRequestLifetimeManager with .Net Core 3.1

### ISSUE THREAD

**Issue by Angus221** [unitycontainer/microsoft-dependency-injection#85]
PerRequestLifetimeManager is in unity.mvc ,but unity.mvc doesn't support NetCoreApp，
how could I use PerRequestLifetimeManager  with asp.net webapi core  3.1?

**Comment by ENikS** [comment]
I am assuming this question is answered and closing the issue. Please let me know if I should reopen.

**Comment by geetmenon** [comment]
> "I think that it's not necessary anymore, you should use Hierarquical Lifetime Manager and add scope on each request."

Could you provide a code sample to do this.
